baseurl = "https://charly3pins.github.io/onepiece/"
disqusShortname = "charly3pins"
footnotereturnlinkcontents = "↩"
googleAnalytics = ""
languageCode = "en-us"
paginate = 10
theme = "hugo-icarus-theme"
title = "ONEPIECE"
[params]
author = "Charly3pins"
avatar = "law.png"
bio = "Collector"
copyright = "Charly3pins"
custom_css = []
custom_js = []
date_format = "2006-01-02T00:00:00+00:00"
disable_mathjax = false
location = "New world"
logo = "/uploads/2018/01/03/oplogo.png"
mainsections = ["post"]
site_description = ""
[params.profile]
follow_button = "https://github.com/charly3pins"
[params.widgets]
categories = true
recent_articles = true
tag_cloud = true
tags = true
[[params.menu]]
before = true
label = "Home"
link = "/"
[[params.menu]]
before = false
label = "Tags"
link = "tags/"
[[params.menu]]
before = false
label = "Categories"
link = "categories/"
[permalinks]
post = "/:year/:month/:day/:slug"
[social]
behance = ""
bitbucket = ""
codepen = ""
deviantart = ""
dribbble = ""
facebook = ""
facebook_admin = ""
flickr = ""
foursquare = ""
github = "charly3pins"
gitlab = ""
googleplus = ""
instagram = ""
jsfiddle = ""
linkedin = ""
medium = ""
pinterest = ""
reddit = ""
slideshare = ""
stackoverflow = ""
tumblr = ""
twitter = "charly3pins"
twitter_domain = ""
vimeo = ""
vine = ""
wordpress = ""
xing = ""
youtube = ""
