# Site settings
baseurl = "https://charly3pins.github.io/onepiece/"
languageCode = "en-us"
title = "P.O.P Guide"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "Portrait of Pirates - The final Guide of figures"
    subtitle = "All related with the P.O.P collection and more!"
    author = "Charly3Pins"
    description = "Hugrid - grid theme for Hugo with an expanding image preview."
    keywords = "One piece, portrait of pirates, pop figures, collectionism, japan, anime, mangac, ollection"

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "Get the theme"

    # Footer text
    footertext = "Made by [ucles83](https://www.facebook.com/joseuclescollection/) and [Charly3Pins](https://twitter.com/charly3pins)"

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']