---
pages:
- post/akainu--sakazuki--p.o.p-dx.md
- post/akainu--sakazuki--p.o.p-neo-dx.md
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- type: tag_list
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
