---
pages:
- post/marco-encore-resale---p.o.p-mas.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: 
- type: tag_list
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
